project:
  type: website
  output-dir: docs
  preview:
    browser: false
    port: 4321

website:
  title: "Marius Energy Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  draft-mode: unlinked

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



